# docker-compose_dev.yml
version: "2"
services:
  app_pro:
    image: reinventing:6.0
    #    build:
    #      context: .
    #      dockerfile: Dockerfile
    restart: always
    environment:
      - TZ=America/Lima
    expose:
      - "80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    # - /Users/kbs/git/peladonerd/varios/1/www:/usr/share/nginx/html:ro
    # - //d/storeDocker/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=reinventing.com.pe,www.reinventing.com.pe
      - LETSENCRYPT_HOST=reinventing.com.pe,www.reinventing.com.pe
      - LETSENCRYPT_EMAIL=miguekos1233@gmail.com
networks:
  default:
    external:
      name: nginx-proxy_nginx-proxy


